// Generated by scripts/gen-figures.mjs — do not edit by hand.
// Width / height of each figure after cropping to its inked content.
export const FIGURE_ASPECT: Record<string, number> = {
  'pageindex': 1.8065,
  'the-cutting-room': 1.6566,
  'echolearn': 5.7658,
  'adaptive-reels': 2.2953,
  'ntk-pruning': 1.1304,
  'table-structure-recognition': 1.3102,
  'facial-emotion-recognition': 2.2036,
  'electronic-nose': 1.2272,
  'hardware-patch-generation': 1.4789,
  'dbms-normalization': 2.8371,
  'toxic-comment-classification': 2.3764,
  'sketch-colorization': 1.7381,
  'cnn-optimization': 1.7927,
  'covid-dashboard': 1.7446,
  'process-scheduling-visualizer': 3.9204,
}
